### ISSUE TITLE
Bugs that cannot complete conversations

### ISSUE THREAD

**Issue by Mabbs** [localuser-isback/Cloudflare-AI#2]
I tried this code, but it seems like it can only reply once and cannot complete the conversation
My instance: https://mabbs.github.io/llama.html

**Comment by localuser-isback** [comment]
Strange, just tested and it seems to be responding just fine.
![image](https://github.com/localuser-isback/Cloudflare-AI/assets/121312523/855895bf-c58e-450c-a57f-53f3dd8e06b8)

**Comment by Mabbs** [comment]
> Strange, just tested and it seems to be responding just fine. ![image](https://private-user-images.githubusercontent.com/121312523/293598592-855895bf-c58e-450c-a57f-53f3dd8e06b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTA5MTMsIm5iZiI6MTcwNDIxMDYxMywicGF0aCI6Ii8xMjEzMTI1MjMvMjkzNTk4NTkyLTg1NTg5NWJmLWM1OGUtNDUwYy1hNTdmLTUzZjNkZDhlMDZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNTUwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmU3YjdjOWI3MDk0NmRiZjAxNWI1NWNlYTFlMGI1ZDQ1NDlkNjFmYjFlMjY1ODU0OWJkZDJjMDhjZjU1ZTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J46kRMkXcCo12R6SIslb7TMR6uVvwvUkbYnKmAtXuKE)

Because I modified the code and removed the multi round dialogue feature, the original code would report errors during multi round conversations. After debugging, I found that the AI returned an object instead of a string during the second reply, so there was an issue checking the format

**Comment by localuser-isback** [comment]
So is this an issue with your modified code or my code, if its with my code make a pull request with changes need to fix otherwise ill probably close this soon unless you got any other questions or issues.

**Comment by Mabbs** [comment]
> So is this an issue with your modified code or my code, if its with my code make a pull request with changes need to fix otherwise ill probably close this soon unless you got any other questions or issues.

No, there is an issue with your code. Now I have modified it to prevent multiple rounds of dialogue to avoid errors. You can try deploying and conducting multiple rounds of dialogue on Cloudflare, and there will definitely be an error message
