### ISSUE TITLE
ccess-Control-Allow-Origin

### ISSUE THREAD

**Issue by 1BitProject** [localuser-isback/Cloudflare-AI#3]
MacosX - IOS
Chrome - Safari - Firefox (Latest Stable Versions)

ON the first request to the worker everything is ok, but on the second request its failign with (index.html:1 Access to XMLHttpRequest at 'mydomainname' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.)

Scripts are stock, and used as mentioned in the Docs.

**Comment by localuser-isback** [comment]
There is a config section that must be modified and replace mydomainname with the website link you are running it on, if you are still having issues send me your config and domain

**Comment by localuser-isback** [comment]
No response, closing this issue. Re-open if you need support
